### ISSUE TITLE
Request to rename artifact-id 'sdk-keygen' to 'hedera-sdk-keygen'

### ISSUE THREAD

**Issue by rafialhamd** [hashgraph/hedera-keygen-java#6]
With reference to another [issue](https://github.com/hashgraph/hedera-sdk-java/issues/69), it's advisable to rename artifact-id **`sdk-keygen`** to **`hedera-sdk-keygen`**, as a standard practice.

**Comment by gregscullard** [comment]
Done, thanks for the suggestion.
