### ISSUE TITLE
Request to move binary files to 'tagged releases'

### ISSUE THREAD

**Issue by rafialhamd** [hashgraph/hedera-keygen-java#7]
Below binary files need to be moved to [tagged releases](https://github.com/hashgraph/hedera-keygen-java/releases) much like [ethereum solidity releases](https://github.com/ethereum/solidity/releases/tag/v0.4.25).

This also helps to **_preserve binaries for each release_** and helpful in locating specific version of binary.

```
target/original-sdk-keygen-1.1.jar
target/sdk-keygen-1.1.jar
```

**Comment by gregscullard** [comment]
Done for v1.0, will do so with releases ongoing.
